### ISSUE TITLE
Units for returned distance of soft_dtw and dtw are different

### ISSUE THREAD

**Issue by CKrawczyk** [tslearn-team/tslearn#100]
After some testing it looks like the `soft_dtw` metric is returning the *square* of the distance, rather than the distance.  I can find no mention of this anywhere in the documentation.

In the case where `gamma` is close to zero both methods should return the same value:

```
from tslearn import metrics
print(metrics.dtw([1.0, 2.0], [3.0, 2.0]))  # returns 2.0
print(metrics.soft_dtw([1.0, 2.0], [3.0, 2.0], gamma=0.01))  # returns 4.0
```

This is especially confusing since using `gamma=0` will return the `dtw` value: https://github.com/rtavenar/tslearn/blob/master/tslearn/metrics.py#L592-L593

I don't necessarily think this is a bug, but it should be documented that these two metrics return different units.

**Comment by rtavenar** [comment]
Thanks for the report @CKrawczyk 

Docs are (finally) improved and return value when gamma is 0 is fixed.
