### ISSUE TITLE
Add UCR/UEA Multivariate TSC datasets

### ISSUE THREAD

**Issue by FlorentF9** [tslearn-team/tslearn#103]
It would be useful for the community to also provide the UCR/UEA Multivariate Time Series Classification (MultivariateTSCProblems) datasets from www.timeseriesclassification.com, even if most algorithms in tslearn cannot handle multivariate TS (yet).

The main issue with this dataset is that the ARFF format is difficult to load in Python. I personally tried a bunch of libraries (scipy, arff, liac-arff, arff2pandas...) and none of these could open the MultivariateTSCProblems files without the parser throwing an exception.

I (and probably many other users) would love to be able to use the MTS datasets as conveniently as the univariate UCR/UEA dataset.

EDIT: I just noticed there was already a PR for this!

**Comment by rtavenar** [comment]
Hi @FlorentF9 

You are perfectly right, and this is work in progress (cf #97 ). We hope to have that as soon as possible.

**Comment by johannfaouzi** [comment]
The latest release of scipy, [scipy 1.3.0](https://pypi.org/project/scipy/1.3.0/), contains a [new feature for loading relational ARFF datasets](https://docs.scipy.org/doc/scipy/reference/release.1.3.0.html#new-features) (which is the case for the multivariate time series datasets) through the [scipy.io.arff.loadarff](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.arff.loadarff.html#scipy.io.arff.loadarff) function.
