### ISSUE TITLE
KShape cluster centers not indexed correctly?

### ISSUE THREAD

**Issue by kushalkolar** [tslearn-team/tslearn#114]
With KShape clustering I often find that the cluster centers don't seem to be the correct cluster center according to their index in KShape.cluster_centers_. The curves within a cluster look similar, but the center with the same cluster index seems to actually be the center of a cluster of a difference index.

Here are some pictures to illustrate: https://drive.google.com/drive/folders/1C4_dcN9GvJ77kS5XvnbUPG114ABmirLs?usp=sharing
For instance the center of Cluster 1 appears to actually be the center of cluster 3.
And the center of Cluster 5 actually appears to be the center of cluster 4.

Also here's a zip containing a numpy array of the input data and the KShape object itself: https://drive.google.com/open?id=1qjoVJJkXBs1zIzVekOKdy9Jce6-ULC9z
The input data can be opened with numpy.load(file_path)
The params used were n_clusters=6, max_iter=300, tol=1e-06, n_init=1, random_state=None

I've tried this with the same data on version 0.1.28.2, 0.1.26, and 0.1.0 and encountered the same issue.

The code I'm using to generate the plots is essentially the same as given in the example in the docs:

```python
for xx in self.input_data[self.y_pred == cluster_num]:
    self.plot.ax_curves.plot(xx.ravel(), 'k-', alpha=0.2)

center = self.ks.cluster_centers_[cluster_num].ravel()
self.plot.ax_curves.plot(center, 'r-')
```

For full context, here the rest of the code where I'm using it. It's basically a simple GUI widget for KShape clustering, with the core functionality based on the example in the docs: https://github.com/kushalkolar/MESmerize/blob/999143376eadb046474f613137b65d1bb4adfdf1/mesmerize/plotting/widgets/kshape/widget.py#L288

Thanks! Please let me know if there's any more information that I can provide.

**Comment by janowskijak** [comment]
I think I might be having as similar issue with Kmeans. I fit and predict on a time-series dataset of shape (365,5760,6) where the first value is the time-series samples, second is length of each time-series and last is the dimension of the multivariate time-series. The cluster centers seem to mix cluster number with dimension value.

**Comment by kushalkolar** [comment]
Not exactly sure what the issue was, but I haven't seen this since v0.2 onward with plenty of datasets.
