### ISSUE TITLE
Derivative DTW or custom distance function

### ISSUE THREAD

**Issue by arvind1609** [tslearn-team/tslearn#180]
Hello Romain,

Thanks for creating this package!

I'm looking for a function to apply derivative DTW or is it possible to modify the distance from euclidean to square of the distance of estimated derivatives described in the picture. Thanks

![derivativedtw](https://user-images.githubusercontent.com/46497657/72164332-7d15a100-3393-11ea-90e0-31e6c7bc76cd.PNG)
.

**Comment by johannfaouzi** [comment]
Isn't it equivalent to modify the input array and to use the Euclidean distance, that is you replace each time series `q` with `D[q]`?

```python
import numpy as np
from tslearn.metrics import dtw

# Create two time series
rng = np.random.RandomState(42)
n_timestamps, n_features = 48, 3
q = rng.randn(n_timestamps, n_features)
c = rng.randn(n_timestamps, n_features)

# Compute their derivatives
D_q = 0.5 * q[2:] + q[1:-1] - 1.5 * q[:-2]
D_c = 0.5 * c[2:] + c[1:-1] - 1.5 * c[:-2]

# Compute the DTW score on the derivatives
dtw(D_q, D_c)
```

**Comment by arvind1609** [comment]
Got it. Thanks!

**Comment by Ninimama** [comment]
I am not sure whether my comment for a closed issue is forcing it to be reopened or not, but please let me ask my question anyway. 

Although modifying the input is easy for such a task, it is difficult to implement the parametric DTW (a combination of DTW and derivative DTW: dist = a*DTW + (1-a)*DDTW). 

I remembered there was another issue regarding independent bi-variate clustering. Although it was explained that the distance can be modified, it is still hard for me to find the part of the code that should be modified as well.

Best,
Nima

**Comment by rtavenar** [comment]
Hi @Ninimama 

Not sure what parametric DTW is. 

Is it a DTW algorithm based on a cost matrix computed as `a * cost_Euc + (1 - a) * cost_Deriv_Euc`? In this case, the new `dtw_path_from_metric` that will be introduced in tslearn v0.4 (already available on master branch though) could help.

Or is it rather a distance that is a weighted sum of DTW and Derivative DTW? In this case, it should not be too difficult to code you own function that takes two time series as input and a weight `a` and return the weighted average.

Maybe what I'm missing is your ultimate goal: what do you want to do with this metric?

**Comment by rtavenar** [comment]
Hi @Ninimama
