### ISSUE TITLE
Distance matrix as input for kmean or other grouping methods

### ISSUE THREAD

**Issue by Ninimama** [tslearn-team/tslearn#182]
Hi,

I have been trying to see if we can give the distance matrix (n-by-b, where n is the number of time series sequences.) as the input for grouping methods such as k-mean or hierarchical clustering. Let's say I define a distance method and I want to see how it works in k-means or let's say I want to modify a DTW distance. 

It is hard to model my distance in a way that can be solved by current tslearn functions. E.g. I want to define a varying-length descriptor for each sample in my ts sequence. Let's say I have two sequences of data: TS1 and TS2, where each has m samples. the distance is the summation of dist( f(TS1[i]),f(TS2[i]) ) for i in 1:m. However, dist( f(TS1[i]),f(TS2[i]) ) is actually DTW( f(TS1[i]) , f(TS2[i]) ). And, the function f might return a new time-series with length p for TS1[i] as its descriptor and length q for TS2[i] !!! 

I understand that finding the centroid, which is important in k-mean, is a challenge (and probably I have to write an optimization problem to find a good centroid based on my distance, like DBA for instance); but, what about Hierarchical Clustering just to see how data objects are grouped to each other? Or what if we prefer to use k-medoid? 

Should I write the whole code from scratch? or can I give the distance matrix and the centroid of each cluster to the k-mean clustering?
 

Sorry for my long question.
Best,
Nima

**Comment by rtavenar** [comment]
Dear @Ninimama 

At the moment, hierarchical clustering is not included in `tslearn`. One way to do it would be to compute a matrix of pairwise distances (maybe using `tslearn` if `dtw` is at stake) and then use `scikit-learn` estimators (eg [this one](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.AgglomerativeClustering.html#sklearn.cluster.AgglomerativeClustering)).

Best,
Romain

**Comment by Ninimama** [comment]
> Dear @Ninimama
> 
> At the moment, hierarchical clustering is not included in `tslearn`. One way to do it would be to compute a matrix of pairwise distances (maybe using `tslearn` if `dtw` is at stake) and then use `scikit-learn` estimators (eg [this one](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.AgglomerativeClustering.html#sklearn.cluster.AgglomerativeClustering)).
> 
> Best,
> Romain

Thanks, Romain, for your input. I would check the scitkit-learn package as well. I think I will use tslearn to calculate dtw distance since it is more straightforward and fast. 

Thanks,
Nima
