### ISSUE TITLE
ValueError: Dimensions (except first) must match! with TimeSeriesKMeans

### ISSUE THREAD

**Issue by vvaghu** [tslearn-team/tslearn#220]
**Describe the bug**
I am getting ValueError: Dimensions (except first) must match! during clustering with TimeSeriesKMeans( 'dtw' and 'softdtw') on time series dataset with dimensions (9295, 7, 1) where 716 of the time series has NaN value at the end. The exception is generated from the predict() method. 
The error disappears when I remove  the time series with NaN at the end.

The printout of the X_train dimensions before fit() and after fit is the same:
Before fit() (9295, 7, 1)
After fit() (9295, 7, 1)

Here is error output:

#-----------------------------------------------------------------------------------
--> 200     _y_pred = _km.predict(_X_train)
    201 
    202     _labels = np.unique(_y_pred)

C:\ProgramData\Anaconda2\envs\py37tf\lib\site-packages\tslearn\clustering.py in predict(self, X)
    867         X = check_array(X, allow_nd=True, force_all_finite='allow-nan')
    868         check_is_fitted(self, 'cluster_centers_')
--> 869         X = check_dims(X, self.cluster_centers_)
    870         X_ = to_time_series_dataset(X)
    871         return self._assign(X_, update_class_attributes=False)

C:\ProgramData\Anaconda2\envs\py37tf\lib\site-packages\tslearn\utils.py in check_dims(X, X_fit, extend)
     67         raise ValueError('Dimensions (except first) must match!'
     68                          ' ({} and {} are passed shapes)'.format(X_fit.shape,
---> 69                                                                  X.shape))
     70 
     71     return X

ValueError: Dimensions (except first) must match! ((8, 6, 1) and (9295, 7, 1) are passed shapes)
#------------------------------------------------------------------------------------

**Environment (please complete the following information):**
 - OS: Windows 10, conda 4.8.2, Python 3.7.6
 - tslearn version 0.3.1

**Comment by GillesVandewiele** [comment]
Hi @vvaghu,

Is it possible that you fitted the model with timeseries having 6 measurements, while making predictions on data with 7 measurements?

**Comment by vvaghu** [comment]
Hi,
No, I am fitting and predicting on the same time series data set. But I see now that 716 time series have NaN values at the start (i.e. the first value) and not at the end. It seems that library does not expect the first value to be NaN.

**Comment by rtavenar** [comment]
Hi @vvaghu 

Thanks for your feedback. Regarding your specific problem, we only allow time series to have nan appended at the end to deal with datasets of variable length time series. 
However, your question raises an important point since for such methods that accept datasets of variable lengths, we should only check the feature dimensionality.

**Comment by rtavenar** [comment]
Probably it could be dealt with in #174

**Comment by rtavenar** [comment]
A fix has been implemented and merged to `dev` branch. It will be available in tslearn v0.4.
