### ISSUE TITLE
Probably an old question  (?)

### ISSUE THREAD

**Issue by Ninimama** [tslearn-team/tslearn#226]
Hello everyone, 

There was a closed issue about implementing Derivative DTW. The answer was satisfactory: taking the derivative of the input before using DTW distance! Although modifying the input is easy for such a task, it is difficult to implement the parametric DTW (a combination of DTW and derivative DTW: dist = a*DTW + (1-a)*DDTW) using the same approach.

I remembered there was another issue regarding independent bi-variate clustering. Although it was explained that the distance can be modified, it is still hard for me to find the part of the code that should be modified as well, and how I should do it. (For example, is there any function like this;

`def DTW_main():
     RETURN DTW
`

Then, if DTW using this main function, I can "easily" manipulate DTW distance myself.

It would be great if there could be some clear explanation of the code written for DTW distance since it can help us to modify it. (and DBA would be calculated accordingly as well).

Best,
Nima

**Comment by rtavenar** [comment]
Hi @Ninimama 

First, it would be nice not to post your message in several issues, as it would lower the amount of work for maintainers.

Not sure what parametric DTW is. 

Is it a DTW algorithm based on a cost matrix computed as `a * cost_Euc + (1 - a) * cost_Deriv_Euc`? In this case, the new `dtw_path_from_metric` that will be introduced in tslearn v0.4 (already available on master branch though) could help.

Or is it rather a distance that is a weighted sum of DTW and Derivative DTW? In this case, it should not be too difficult to code you own function that takes two time series as input and a weight `a` and return the weighted average.

Maybe what I'm missing is your ultimate goal: what do you want to do with this metric?

**Comment by rtavenar** [comment]
By the way, if you plan to use DBA: DBA relies on the path extracted by DTW, so it would make sense to use it only in the first case (when a single path is extracted) but not in the second one, since DTW and DDTW will not return a single path.

**Comment by Ninimama** [comment]
Hi @rtavenar Romain,

Thanks for your response. I am a newbie in using Github. I will make sure to post only one clear message for an issue.

I think I just realized what my problem is. My focus has been on clustering and I would like to consider some new versions of DTW distance: such as a*DTW(x,y) + (1-a)*DDTW(x.y), the latter case you mentioned,  or independent distance in a bivariate data analysis: dist([x1,y1],[x2,y2]) = dist(x1,x2) + dist(y1,y2). However, I realized that it is hard for implementing them for the clustering purpose since you mentioned DBA is calculated based on the extracted DTW path, which is not unique in both two distances I mentioned earlier.

I hope my explanation clarifies what I was looking for in my previous. Thanks for your constructive insight.

Best,
Nima

**Comment by rtavenar** [comment]
Well, in this case, optimization on your two variables are disjoint and you could probably just use DBA on each separate modality.

**Comment by rtavenar** [comment]
Let me know if I can close this issue since it seems to be a rather individual issue that is not likely to get implemented in tslearn, right?

**Comment by Ninimama** [comment]
Yes, I think it is an individual issue. You are right. Thanks for sharing your insight on this.
