### ISSUE TITLE
Record more information for all models when dumping to disk

### ISSUE THREAD

**Issue by rtavenar** [tslearn-team/tslearn#230]
**Is your feature request related to a problem? Please describe.**
I just noticed while working on a personal project that for kmeans, only the cluster centers were dumped to disk when using `to_*` functions. 

In my case, I would have liked to have access to predicted labels, to avoid recomputing them afterwards. I just changed it for kmeans in a commit, but it would be nice to check if the same thing should be done for other estimators. Also, maybe if someone wants to work on a PR to fix this, it could be nice to have a place somewhere were we list all provided attributes and then have `_get_model_params` and `_is_fitted` rely on this one.

If you want to work on this, please let us know by answering to this thread.

**Comment by rtavenar** [comment]
Typically, what I did for kmeans can be seen [here](https://github.com/tslearn-team/tslearn/commit/41d395c3ab0fb362099ec90939c552ea25761506).
So a first step would be to do the same for all estimators in tslearn (just go through the docs and checks the documented attributes for each estimator).

**Comment by kushalkolar** [comment]
I think simply saving all non-callable model attributes which end in `_` should do this?

One minor concern is how to separate model attributes that correspond to the model itself (ex. cluster centers) vs. attributes that correspond to the data the model was trained on (such as labels). Or should there just be a note in the documentation for the user to be aware of this?

**Comment by rtavenar** [comment]
> I think simply saving all non-callable model attributes which end in `_` should do this?

Probably, yes.

> One minor concern is how to separate model attributes that correspond to the model itself (ex. cluster centers) vs. attributes that correspond to the data the model was trained on (such as labels). Or should there just be a note in the documentation for the user to be aware of this?

Then, the question is: is it worse to save too many things or too few things. I'd say that most `tslearn` models are of moderate size, hence saving too many things should not be an issue and would guarantee that. once reloaded, the model has the exact same behaviour as it had before being dump to disk, which is the expected behavior, I think.

**Comment by rtavenar** [comment]
@kushalkolar : is there a reason not to record all attributes?

**Comment by kushalkolar** [comment]
@rtavenar sorry for the late response. Yup I agree with your point. I was previously thinking about a model just being useful for predictions. I think it's intuitive for the object to have the same behavior as it did before being dumped to disk.

**Comment by rtavenar** [comment]
And would you be available for a quick PR that would implement that?

**Comment by kushalkolar** [comment]
I'd be interested to try out next week if that's not too late?

**Comment by rtavenar** [comment]
That would be ok

Sent from a mobile device. Please excuse my brevity.

________________________________

**Comment by rtavenar** [comment]
@kushalkolar did you have time to have a look at this issue ?

**Comment by kushalkolar** [comment]
@rtavenar sorry I haven't had the time to dig into this. I don't think I'll be able to until June so please go ahead if you need this soon.
