### ISSUE TITLE
Kmeans cluster init to control cluster shapes

### ISSUE THREAD

**Issue by ssimontacchi** [tslearn-team/tslearn#234]
Hi,

I have some common shapes in the data that I would like the TSKMeans clusters to look like. 

I tried using the init method on the both the normalized and unnormalized trends in the data (which is right?) but both ways actually found that all the data was predicted to be in just one of the clusters.

Any idea how to use init better or control the cluster shapes?

**Comment by rtavenar** [comment]
Hi @ssimontacchi 

Could you detail a bit on what init method you are using at the moment. Could you for example provide a code snippet?

**Comment by ssimontacchi** [comment]
Hi @rtavenar,

My apologies... it looks like there was just a formatting error on my side. 

If anyone else is having trouble with init, it is as simple as passing a list of np.arrays. My data is 2d (time-series), but I only needed to pass my y-values, like:
`init = to_time_series_dataset([y1_normalized, y2_normalized, y3_normalized])`

Thanks @rtavenar for the support!!
