### ISSUE TITLE
Docs: some references are ill formatted

### ISSUE THREAD

**Issue by rtavenar** [tslearn-team/tslearn#238]
**Is your feature request related to a problem? Please describe.**
Some of the references are ill-formatted in the docs (because alignments are not set as expected by numpydoc I think), cf screenshot:
<img width="786" alt="numpydoc" src="https://user-images.githubusercontent.com/18221203/82421573-7e618380-9a81-11ea-814d-a6194f1a6190.png">

().

**Describe the solution you'd like**

EDIT: We would expect the ref numbering to be `[1]`.
This seems to happen only where references are used in class docstrings (not in method docstrings for example)

This should be fixed everywhere needed. Help much appreciated!

**Comment by GillesVandewiele** [comment]
Hi @rtavenar,

I will do this quickly! :)

**Comment by rtavenar** [comment]
Hum, it seems this bug was due to `numpydoc` and by upgrading to version 1.0.0.dev0 does the trick (cf. `latest` docs). @GillesVandewiele I am really sorry that I wasted your time :/ I think I can close your PR, let me know if this is not the case.

**Comment by GillesVandewiele** [comment]
That's no problem at all @rtavenar! You can indeed close the PR.
