### ISSUE TITLE
How to extract the elements from the species cluster in Tslearn

### ISSUE THREAD

**Issue by daibitao19** [tslearn-team/tslearn#240]
I'm am a beginner of tslearnI use tslearn time cluster, I completed the clustering based on documentation, but I don't know how to extract the elements in the cluster, tslearn data format requirements are three-dimensional array (n, sz, dimenation), and there can be a string, I see fit to predict function, it told me to return to the Index of the cluster each sample belongs to. But I do not understand the output results.I would like to consult you.Because the data format cannot contain strings, I also thought about using a 4-dimensional array to label, but the TXT made according to the format requirements does not seem to be able to achiev
![微信图片_20200522232913](https://user-images.githubusercontent.com/58027024/82685700-3318c200-9c87-11ea-849b-c2bf0836572d.png)
![微信图片_202005222329131](https://user-images.githubusercontent.com/58027024/82685706-34e28580-9c87-11ea-8aac-9ea746c1cc12.png)
![微信图片_202005222329132](https://user-images.githubusercontent.com/58027024/82685707-3613b280-9c87-11ea-86a4-1586a47956c7.png)
![微信图片_202005222329133](https://user-images.githubusercontent.com/58027024/82685709-36ac4900-9c87-11ea-8121-b0d6dd0402ce.png)
[monday - 副本.txt](https://github.com/tslearn-team/tslearn/files/4669098/monday.-.txt)
`from tslearn.utils import save_time_series_txt, load_time_series_txt
import numpy as np
import numpy
import matplotlib.pyplot as plt

from tslearn.clustering import KShape
from tslearn.datasets import CachedDatasets
from tslearn.preprocessing import TimeSeriesScalerMeanVariance
from tslearn.clustering import GlobalAlignmentKernelKMeans
from tslearn.metrics import sigma_gak
from tslearn.clustering import TimeSeriesKMeans
time_series_dataset = load_time_series_txt("monday - 副本.txt")
X_train=time_series_dataset
X_train.shape
#np.random.shuffle(X_train)
# For this method to operate properly, prior scaling is required
#seed = 0
#numpy.random.seed(seed)
sz = X_train.shape[1]
# DBA-k-means
print("DBA k-means")
dba_km = TimeSeriesKMeans(n_clusters=3,
                          n_init=2,
                          metric="dtw",
                          verbose=True,
                          max_iter_barycenter=10)
y_pred = dba_km.fit_predict(X_train)
for yi in range(3):
    #plt.subplot(3, 3, 4 + yi)
    for xx in X_train[y_pred == yi]:
        plt.plot(xx.ravel(), "k-", alpha=.2)
    plt.plot(dba_km.cluster_centers_[yi].ravel(), "-")
    plt.xlim(0, sz)
    #plt.ylim(-1.2,1.5)
    plt.text(0.55, 0.85,'Cluster %d' % (yi + 1),
             transform=plt.gca().transAxes)
    if yi == 1:
        plt.title("DBA $k$-means")
        
plt.figure()
for yi in range(3):
    #plt.subplot(4, 1, 1 + yi)
    #for xx in X_train[y_pred == yi]:
        #plt.plot(xx.ravel(), "k-", alpha=.2)
    plt.plot(dba_km.cluster_centers_[yi].ravel(), "-")
    plt.xlim(0, sz)
    #plt.ylim(-1.2,1.5)
    plt.title("Cluster %d" % (yi + 1))

plt.tight_layout()
plt.show()
        
for yi in range(3):
    #plt.subplot(3, 3, 4 + yi)
    #for xx in X_train[y_pred == yi]:
        #plt.plot(xx.ravel(), "k-", alpha=.2)
    plt.plot(dba_km.cluster_centers_[yi].ravel(), "-")`

e this function.Now I have a 120-country, 9-day, 1-dimensional data, code data set and running results shown here

**Comment by rtavenar** [comment]
Hi @daibitao19 

I'm not sure I fully get your question, but if you refer to the example in the gallery, then, the code `X_train[y_pred == yi]` extracts the time series from `X_train` that were clustered in cluster `yi`.

**Comment by daibitao19** [comment]
My goal is to extract elements from each cluster, which I'm not making clear here.Because there are nine days of time series data for 120 countries, I want to see what countries are in each cluster after classification.Because tslearn requires that the data format not contain strings, I was unable to enter the country label.Although by printing y-pred you can see the class to which each row of elements belongs.My first question is whether there is a way to directly label the data so that I can directly extract the name or label of the country in each cluster.One way I thought about it was I would make a list of 120 countries and index them using y-pred=0 -- n.. The second question I would like to ask y_pred = dba_km fit_predict (X_train) predict the closest cluster each time series in X belongs to. But I did not understand to return as a result, I divided into three categories, for example, it shows init10.075 - & gt;0.060 - & gt;0.057 - & gt; 
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 360 out of 360 | elapsed: 0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 360 out of 360 | elapsed: 0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 360 out of 360 | elapsed: 0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 360 out of 360 | elapsed: 0.0s finished
0.056 - & gt;0.056 - & gt; 
Init 2
0.101 - & gt;0.057 - & gt;0.057 - & gt;0.057 - & gt; 
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 360 out of 360 | elapsed: 0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 360 out of 360 | elapsed: 0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 360 out of 360 | elapsed: 0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 360 out of 360 | elapsed: 0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 360 out of 360 | elapsed: 0.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 360 out of 360 | elapsed: 0.0s finished

**Comment by daibitao19** [comment]
Could you please explain it for me?

**Comment by GillesVandewiele** [comment]
Hi @daibitao19,

You're proposal (or that of Romain) seems fine. Get the indices of timeseries assigned to a cluster and get their respective countries.

What you see printed to stdout is the inertia (https://github.com/tslearn-team/tslearn/blob/master/tslearn/clustering.py#L160). You can disable it by setting `verbose` to `False`.

**Comment by daibitao19** [comment]
You've done me a big favor.Thanks a lot.
