### ISSUE TITLE
Tensorflow error in learning shaplets example

### ISSUE THREAD

**Issue by AdeLouis** [tslearn-team/tslearn#251]
Hi! I have been trying to run the example code provided on tslearn for learning shapelets but keep running into the same TensorFlow issue.  I run the code on both google colab and on my desktop using jupyter notebook through anaconda. 
The error is on this line of code: 

`shp_clf.fit(X_train, y_train)`

I get a value error that says: 

> alueError: Tensor-typed variable initializers must either be wrapped in an init_scope or callable (e.g., `tf.Variable(lambda : tf.truncated_normal([10, 40]))`) when building functions. Please file a feature request if this restriction inconveniences you.

I can post the entire error if that's helpful. Unsure if this is a tslearn issue or TensorFlow issue. I changed nothing about the code and ran it as is.  

The Tensorflow version is used is: 2.1.0

Thanks for the help!

**Comment by AdeLouis** [comment]
**To reproduce**

Simply run the python script or .ipynb file on learning shapelets from the tslearn website: [learning shaplets](https://tslearn.readthedocs.io/en/stable/auto_examples/classification/plot_shapelets.html#sphx-glr-auto-examples-classification-plot-shapelets-py)

**Comment by rtavenar** [comment]
Hi @AdeLouis 

In tslearn up to version 0.3.*, we rely on TF1. 
This is very likely to change in our next release. In fact, we are very close to merging the code refactor that would make the `shapelets` module rely on TF2 (cf. our Pull Request #126 ). As soon as this will be merged to master, you will be able to use it following [the instructions to install latest github-hosted version](https://tslearn.readthedocs.io/en/stable/installation.html#using-latest-github-hosted-version).

So, if you need a fix TODAY, I'd suggest you roll back to TF1.16 and if you can wait for a few days, I'd suggest you do so and try installing latest `tslearn` once #126 is merged to master.

**Comment by AdeLouis** [comment]
Oh, this was a quick response. Thank you very much. Will rollback to TF1.16 but will check back later an update tslearn to the newest version. 

Thanks!

**Comment by AdeLouis** [comment]
TF 1.16 doesn't seem to exit but downgraded to 1.15 and now works. Thanks again

**Comment by rtavenar** [comment]
FYI #126 is now merged to master

**Comment by AdeLouis** [comment]
Oh great. Will update thank you!

**Comment by AdeLouis** [comment]
To update to latest version do I use the github hosted version installation?

**Comment by rtavenar** [comment]
Yes, and do not forget to add --upgrade to your pip command
