### ISSUE TITLE
Method to transform X to distance-cluster space

### ISSUE THREAD

**Issue by ACLCabatingan** [tslearn-team/tslearn#253]
In [tslearn.clustering.TimeSeriesKMeans](https://github.com/tslearn-team/tslearn/blob/9d20ed0991bfc676269ad1c9ee2c87c29b484e19/tslearn/clustering.py#L526-L874):

There's currently no direct way of getting top N 'closest' time-series curves to a given sample curve.
This could be resolved if we have a method  that transforms X to _distance-cluster space_ similar  to [sklearn.cluster.KMeans's](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html#sklearn.cluster.KMeans.transform) transform method.

**Comment by rtavenar** [comment]
Hi @ACLCabatingan 
Good catch ! 
Would you be willing to implement it ?
