### ISSUE TITLE
Implement Matrix Profile Data Structure

### ISSUE THREAD

**Issue by unnamedplay-r** [tslearn-team/tslearn#27]
A matrix profile is a data structure built from a similarity join of two time series. The resulting data structure produces two objects: 

1. An array containing the **_indices_** of the nearest neighbor (a subsequence that has the minimum Euclidean distances to it) 
2. Their respective Euclidean distances. 

Once the data structure is built, it can produce responses to:

1. Time Series Set Similarity and Difference
2. Motif discovery
3. Discord discovery
4. Shapelet discovery
5. Semantic segmentation
6. Density estimation

Resources:

1. http://www.cs.ucr.edu/~eamonn/MatrixProfile.html
2. [Original Paper](http://www.cs.ucr.edu/~eamonn/PID4481997_extend_Matrix%20Profile_I.pdf)
2. Lecture [Part 1](https://www.youtube.com/watch?v=1ZHW977t070) and [Part 2](https://www.youtube.com/watch?v=LnQneYvg84M).
3. An implementation we might want to review: https://github.com/rob-med/owlpy

**Comment by vanbenschoten** [comment]
@unnamedplay-r @rtavenar We've implemented Matrix Profile and a lot of additional functionality as a Python package called "matrixprofile-ts" (https://github.com/target/matrixprofile-ts). We're going to continue expanding the package over time, so it might be a useful dependency that can leverage many of the tslearn functions.

**Comment by rtavenar** [comment]
Hi @vanbenschoten 

Thanks for the suggestion. Implementing a tslearn estimator that would rely on your package (that is what you suggest, right?) would be a reasonable option imho. That would mean we would add your package as a soft requirement as we do for keras for shapelets. 
Would you be ok to start a PR on which we could work together ?

**Comment by vanbenschoten** [comment]
@rtavenar sounds good. I'll take a look and open a PR.

**Comment by vanbenschoten** [comment]
@rtavenar apologies for the delay: we're in the process of re-factoring the matrixprofile-ts code so that there's a common structural format between the Matrix Profile libraries in Python, R and Golang. That process should wrap up in the next few weeks, at which point I'll start working on the PR.

**Comment by rtavenar** [comment]
#250 implements a basic transformer for Matrix Profiles. When it will be merged to master, this will close this Issue. If you want to work on a better implementation / more features related to matrix profiles, do not hesitate to re-open.
