### ISSUE TITLE
Error when using the Time Series K-means with data of variable length - II

### ISSUE THREAD

**Issue by AntaresII** [tslearn-team/tslearn#292]
Salut professor Tavenard. I encountered the following error using tslearn:

**Describe the bug**
When input consists of timeseries are of unequal length TimeSeriesKMeans throws a NaN error.
Error message: "ValueError: Input contains NaN, infinity or a value too large for dtype('float64')."
The code works when timeseries are of equal length.

**To Reproduce**
import tslearn
import matplotlib.pyplot as plt, pandas as pd, numpy as np
from tslearn.utils import to_time_series_dataset

X  = [-0.070024,-0.011244,-0.048864]
Y  = [-0.046507,-0.032194,0.065276]
Z  = [0.065012,0.078344]

xyz_all = to_time_series_dataset([X,Y,Z])

from tslearn.clustering import TimeSeriesKMeans
from tslearn.datasets import CachedDatasets
from tslearn.preprocessing import TimeSeriesScalerMeanVariance, \
    TimeSeriesResampler

seed = 0
numpy.random.seed(seed)

print("Euclidean k-means")
km = TimeSeriesKMeans(n_clusters=3, verbose=True, random_state=seed)
y_pred = km.fit_predict(xyz_all)

**Environment:**
- windows 10
- python version 3.7.4
- tslearn version 0.4.1

**Error message:**
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-45-c6fc926392aa> in <module>
     25 print("Euclidean k-means")
     26 km = TimeSeriesKMeans(n_clusters=3, verbose=True, random_state=seed)
---> 27 y_pred = km.fit_predict(xyz_all)
     28 
     29 # print(AX)

c:\users\big deal\appdata\local\programs\python\python37\lib\site-packages\tslearn\clustering.py in fit_predict(self, X, y)
   1011         """
   1012         X = check_array(X, allow_nd=True, force_all_finite='allow-nan')
-> 1013         return self.fit(X, y).labels_
   1014 
   1015     def predict(self, X):

c:\users\big deal\appdata\local\programs\python\python37\lib\site-packages\tslearn\clustering.py in fit(self, X, y)
    978                     print("Init %d" % (n_successful + 1))
    979                 n_attempts += 1
--> 980                 self._fit_one_init(X_, x_squared_norms, rs)
    981                 if self.inertia_ < min_inertia:
    982                     best_correct_centroids = self.cluster_centers_.copy()

c:\users\big deal\appdata\local\programs\python\python37\lib\site-packages\tslearn\clustering.py in _fit_one_init(self, X, x_squared_norms, rs)
    831                     self.n_clusters,
    832                     x_squared_norms,
--> 833                     rs
    834                 ).reshape((-1, sz, d))
    835             else:

c:\users\big deal\appdata\local\programs\python\python37\lib\site-packages\sklearn\cluster\_kmeans.py in _k_init(X, n_clusters, x_squared_norms, random_state, n_local_trials)
     98     closest_dist_sq = euclidean_distances(
     99         centers[0, np.newaxis], X, Y_norm_squared=x_squared_norms,
--> 100         squared=True)
    101     current_pot = closest_dist_sq.sum()
    102 

c:\users\big deal\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\pairwise.py in euclidean_distances(X, Y, Y_norm_squared, squared, X_norm_squared)
    260     paired_distances : distances betweens pairs of elements of X and Y.
    261     """
--> 262     X, Y = check_pairwise_arrays(X, Y)
    263 
    264     # If norms are passed as float32, they are unused. If arrays are passed as

c:\users\big deal\appdata\local\programs\python\python37\lib\site-packages\sklearn\metrics\pairwise.py in check_pairwise_arrays(X, Y, precomputed, dtype, accept_sparse, force_all_finite, copy)
    142         Y = check_array(Y, accept_sparse=accept_sparse, dtype=dtype,
    143                         copy=copy, force_all_finite=force_all_finite,
--> 144                         estimator=estimator)
    145 
    146     if precomputed:

c:\users\big deal\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, warn_on_dtype, estimator)
    576         if force_all_finite:
    577             _assert_all_finite(array,
--> 578                                allow_nan=force_all_finite == 'allow-nan')
    579 
    580     if ensure_min_samples > 0:

c:\users\big deal\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py in _assert_all_finite(X, allow_nan, msg_dtype)
     58                     msg_err.format
     59                     (type_err,
---> 60                      msg_dtype if msg_dtype is not None else X.dtype)
     61             )
     62     # for object dtype data, we only check for NaNs (GH-13254)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by AntaresII** [comment]
Ugh, just read in the documentation: 

"Notes: If metric is set to “euclidean”, the algorithm expects a dataset of equal-sized time series."

That is sad :(

**Comment by GillesVandewiele** [comment]
Hi @AntaresII,

The problem, and why it is not supported, is that it is hard to find a "standard" definition of euclidean distances when they do not have the same length. Perhaps you could look in DTW? That will align the shorter signal to the longer ones, and is supported for variable length inputs.

**Comment by AntaresII** [comment]
Hello GillesVandewiele, appreciate your response. I was hoping to avoid DTW. It's never straight forward :)
