### ISSUE TITLE
[kernel k-means with GAK] Whole matching vs subsequence matching

### ISSUE THREAD

**Issue by MAlexandraOliveira** [tslearn-team/tslearn#293]
Hi there,

I would like to know if the kernel k-means with GAK is using a whole sequence matching rather than a subsequence matching when calculating the similarity between time-series.

Thanks in advance!

**Comment by rtavenar** [comment]
Hi @MAlexandraOliveira 

Yes, it is using Global Alignment Kernel, which is a whole sequence matching kernel.
