### ISSUE TITLE
to_json() fails if self.init is set to be an ndarray

### ISSUE THREAD

**Issue by PercyLau** [tslearn-team/tslearn#304]
**Describe the bug**
to_json() fails if self.init is set to be an ndarray

**A Simple Pseudocode To Reproduce**
last_km = TimeSeriesKMeans.from_json('last_model.json')
last_centroids = last_km.cluster_centers_
km = TimeSeriesKMeans(n_clusters = 3, init=last_centroids)
km.fit(data_set)
km.to_json('new_model.json')

**Expected behavior**
It seems self.init does not properly series the input ndarray

**Environment (please complete the following information):**
 - OS: Windows, Linux
 - tslearn version 0.4.1

**Comment by rtavenar** [comment]
I guess this is related to #300 

@kushalkolar is working on a fix at the moment

**Comment by rtavenar** [comment]
Now fixed in master.

**Comment by PercyLau** [comment]
Great！
