### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.cluster.k_means_'

### ISSUE THREAD

**Issue by philip-zelichenko** [tslearn-team/tslearn#327]
**Describe the bug**
ModuleNotFoundError error when importing  'from tslearn.clustering import TimeSeriesKMeans'

**To Reproduce**
'from tslearn.clustering import TimeSeriesKMeans'

**Expected behavior**
no error

**Environment (please complete the following information):**
 - OS: Linux 2020 x86_64 x86_64 x86_64 GNU/Linux
 - tslearn version '0.4.1'

**Additional context**
tslearn is trying to import 'ModuleNotFoundError: No module named 'sklearn.cluster.k_means_'
although the module name is '_kmeans' under sklearn '0.24.0'

**Comment by shima-create** [comment]
Has this bug been solved?
Is it possible to install another version of tslearn or scikit-learn to solve the issue?

**Comment by chusloj** [comment]
@philip-zelichenko The `scikit-learn` docs show that the `_k_means` module has been changed to [`KMeans`](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html). I'll open a PR soon to address this in `clustering.py`.

**Comment by rtavenar** [comment]
Thanks @chusloj to work on this. While waiting for the fix, one can roll back to sklearn 0.23.* for the clustering module in tslearn to work properly.

**Comment by rtavenar** [comment]
This is now fixed in master (and will be available in our next release).
