### ISSUE TITLE
KShape unimportable 

### ISSUE THREAD

**Issue by setholinger** [tslearn-team/tslearn#339]
It appears that the sklearn has renamed 'sklearn.cluster.k_means_' to 'sklearn.cluster.kmeans'. This renders Kshape unable to be imported. The example below should produce the error that follows it. This could be fixed on the user end by renaming the sklearn file, but this would likely break some other codes. Thanks for an awesome package!

```
conda create --name py38 python=3.8
conda activate py38
conda install tslearn
python
>>> from tslearn.clustering import KShape
```

> 
> Traceback (most recent call last):
>   File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/tslearn/clustering.py", line 13, in <module>
>     from sklearn.cluster._k_means import _k_init
> ModuleNotFoundError: No module named 'sklearn.cluster._k_means'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/tslearn/clustering.py", line 16, in <module>
>     from sklearn.cluster.k_means_ import _k_init
> ModuleNotFoundError: No module named 'sklearn.cluster.k_means_'
>

**Comment by rtavenar** [comment]
Hi @setholinger 

You are right. This problem is now fixed on master, and the next release we are preparing at the moment will include this fix. Another temporary hack is to use sklearn 0.23 that is fully compatible.

Related to #327 and #328

**Comment by setholinger** [comment]
Thank you, much appreciated!
