### ISSUE TITLE
ImportError: cannot import name '_check_sample_weight' from 'sklearn.utils.validation' 

### ISSUE THREAD

**Issue by JavierRuano** [tslearn-team/tslearn#351]
ImportError                               Traceback (most recent call last)
<ipython-input-13-e72137c5b775> in <module>
----> 1 from tslearn.clustering import TimeSeriesKMeans
      2 seed = 0
      3 import numpy as np
      4 np.random.seed(seed)
      5 model = TimeSeriesKMeans(n_clusters=12, metric="dtw",

C:\ProgramData\Anaconda3\lib\site-packages\tslearn\clustering\__init__.py in <module>
      9 from .utils import (EmptyClusterError, silhouette_score,
     10                     TimeSeriesCentroidBasedClusteringMixin)
---> 11 from .kmeans import (TimeSeriesKMeans, KernelKMeans,
     12                      GlobalAlignmentKernelKMeans)
     13 

C:\ProgramData\Anaconda3\lib\site-packages\tslearn\clustering\kmeans.py in <module>
      4 from sklearn.utils import check_random_state
      5 from sklearn.utils.extmath import stable_cumsum
----> 6 from sklearn.utils.validation import _check_sample_weight
      7 from scipy.spatial.distance import cdist
      8 import numpy

ImportError: cannot import name '_check_sample_weight' from 'sklearn.utils.validation' (C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py)

Windows 10
python 3.7.4

**Comment by GillesVandewiele** [comment]
What's your sklearn version?

**Comment by JavierRuano** [comment]
python: 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\cancelote_of_the_lake\anaconda3\python.exe
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
          pip: 20.2.4
   setuptools: 50.3.1.post20201107
      sklearn: 0.23.2
        numpy: 1.19.2
        scipy: 1.5.2
       Cython: 0.29.21
       pandas: 1.1.3
   matplotlib: 3.3.2
       joblib: 0.17.0
threadpoolctl: 2.1.0

Built with OpenMP: True

**Comment by GillesVandewiele** [comment]
tslearn requires sklearn > 0.24.0

`pip install sklearn --upgrade` should do the trick!

**Comment by JavierRuano** [comment]
Ok, thanks.
