### ISSUE TITLE
Minor typo in readme for installation

### ISSUE THREAD

**Issue by mstickle** [tslearn-team/tslearn#359]
**Describe the bug**
Instructions for installation using git for tslearn gives the wrong link resulting in HTTP ERROR 404. The link wasn't updated when the master branch was renamed to main.

![Screen Shot 2021-07-29 at 1 37 20 PM](https://user-images.githubusercontent.com/32178910/127562395-5f11e274-972d-4331-b65a-537d8e164882.png)

**To Reproduce**
Run:
`python -m pip install https://github.com/tslearn-team/tslearn/archive/master.zip`

**Expected behavior**
Command should be:
`python -m pip install https://github.com/tslearn-team/tslearn/archive/main.zip`
This effectively resolved the 404 issue explained above.

**Environment (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - tslearn: v0.5.1.0

**Comment by rtavenar** [comment]
Hi,

Thanks for the feedback. This is now fixed in https://github.com/tslearn-team/tslearn/releases/tag/v0.5.2

**Comment by mstickle** [comment]
Thank you! Have a good day!
