### ISSUE TITLE
Publish wheels for Python 3.9

### ISSUE THREAD

**Issue by petoknm** [tslearn-team/tslearn#372]
I am using python 3.9 (soon 3.10, but I'll keep that for another day) and my CI/CD process takes a long time, often spending 5min on just building tslearn.
I would like to have cp39 wheels available on pypi.
Thank you

**Comment by petoknm** [comment]
I would love to submit a PR but I'm not quite sure where to find the packaging scripts.

**Comment by rtavenar** [comment]
Hi @petoknm 

So things are done there as a GitHub Action: https://github.com/tslearn-team/tslearn/blob/main/.github/workflows/build_wheels.yml

It relies on https://github.com/pypa/cibuildwheel and I am unsure why cp39 is not considered :/ Maybe our cibuildwheel version is too old... If you could investigate that, it would be more than welcome!

**Comment by petoknm** [comment]
`cibuildwheel` is fixed to version 1.3.0 [here](https://github.com/tslearn-team/tslearn/blob/main/.github/workflows/build_wheels.yml#L29), which does not support python 3.9.
According to the [changelog](https://cibuildwheel.readthedocs.io/en/stable/changelog/), python 3.9 support was added in version 1.6.0.

I'll try to upgrade to the latest 1.x release for hopefully a quick fix, but 2.x is already out, so maybe the project should also look into upgrading to 2.x.

**Comment by petoknm** [comment]
From my preliminary look at 2.0.0 changelog, the main breaking change is the removal of python 3.5 support.
So it would also fix #316

**Comment by rtavenar** [comment]
Yep, no problem with that.
