### ISSUE TITLE
Unable to install tslearn

### ISSUE THREAD

**Issue by Ishaanjolly** [tslearn-team/tslearn#389]
Hi, I recently install tensorflow on my M1 mac. Post which, I was trying to install tslearn. However, I am getting some strange error that I have not encountered before. The error is below: 
`ERROR: Failed building wheel for numba
?25h  Running setup.py clean for numba
  Building wheel for llvmlite (setup.py) ... ?25lerror
  ERROR: Command errored out with exit status 1:
   command: /Users/ishaanjolly/miniforge3/envs/tensorflow/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-install-8hllkr24/llvmlite_8b48c7dc9d54495d8cdd0cb42c8df407/setup.py'"'"'; __file__='"'"'/private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-install-8hllkr24/llvmlite_8b48c7dc9d54495d8cdd0cb42c8df407/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-wheel-s2p9mg2t
       cwd: /private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-install-8hllkr24/llvmlite_8b48c7dc9d54495d8cdd0cb42c8df407/
  Complete output (11 lines):
  running bdist_wheel
  /Users/ishaanjolly/miniforge3/envs/tensorflow/bin/python /private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-install-8hllkr24/llvmlite_8b48c7dc9d54495d8cdd0cb42c8df407/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-install-8hllkr24/llvmlite_8b48c7dc9d54495d8cdd0cb42c8df407/ffi/build.py", line 220, in <module>
      main()
    File "/private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-install-8hllkr24/llvmlite_8b48c7dc9d54495d8cdd0cb42c8df407/ffi/build.py", line 214, in main
      main_posix('osx', '.dylib')
    File "/private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-install-8hllkr24/llvmlite_8b48c7dc9d54495d8cdd0cb42c8df407/ffi/build.py", line 134, in main_posix
      raise RuntimeError(msg) from None
  RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
  error: command '/Users/ishaanjolly/miniforge3/envs/tensorflow/bin/python' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
?25h  Running setup.py clean for llvmlite
Failed to build numba llvmlite
Installing collected packages: llvmlite, numba, Cython, tslearn
    Running setup.py install for llvmlite ... ?25lerror
    ERROR: Command errored out with exit status 1:
     command: /Users/ishaanjolly/miniforge3/envs/tensorflow/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-install-8hllkr24/llvmlite_8b48c7dc9d54495d8cdd0cb42c8df407/setup.py'"'"'; __file__='"'"'/private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-install-8hllkr24/llvmlite_8b48c7dc9d54495d8cdd0cb42c8df407/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-record-vtm8oibp/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ishaanjolly/miniforge3/envs/tensorflow/include/python3.9/llvmlite
         cwd: /private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-install-8hllkr24/llvmlite_8b48c7dc9d54495d8cdd0cb42c8df407/
    Complete output (14 lines):
    running install
    running build
    got version from file /private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-install-8hllkr24/llvmlite_8b48c7dc9d54495d8cdd0cb42c8df407/llvmlite/_version.py {'version': '0.38.0', 'full': 'f0365b91ce1e1f74c68785c6d0067f32f89857d9'}
    running build_ext
    /Users/ishaanjolly/miniforge3/envs/tensorflow/bin/python /private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-install-8hllkr24/llvmlite_8b48c7dc9d54495d8cdd0cb42c8df407/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-install-8hllkr24/llvmlite_8b48c7dc9d54495d8cdd0cb42c8df407/ffi/build.py", line 220, in <module>
        main()
      File "/private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-install-8hllkr24/llvmlite_8b48c7dc9d54495d8cdd0cb42c8df407/ffi/build.py", line 214, in main
        main_posix('osx', '.dylib')
      File "/private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-install-8hllkr24/llvmlite_8b48c7dc9d54495d8cdd0cb42c8df407/ffi/build.py", line 134, in main_posix
        raise RuntimeError(msg) from None
    RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
    error: command '/Users/ishaanjolly/miniforge3/envs/tensorflow/bin/python' failed with exit code 1
    ----------------------------------------
?25hERROR: Command errored out with exit status 1: /Users/ishaanjolly/miniforge3/envs/tensorflow/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-install-8hllkr24/llvmlite_8b48c7dc9d54495d8cdd0cb42c8df407/setup.py'"'"'; __file__='"'"'/private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-install-8hllkr24/llvmlite_8b48c7dc9d54495d8cdd0cb42c8df407/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/z7/qz25djs97_vfp299dqb664300000gn/T/pip-record-vtm8oibp/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ishaanjolly/miniforge3/envs/tensorflow/include/python3.9/llvmlite Check the logs for full command output.`

**Comment by GillesVandewiele** [comment]
You might have to install llvm independently (e.g. through brew)

https://github.com/numba/llvmlite/issues/531

**Comment by Ishaanjolly** [comment]
Hi, I was able to resolve the issue by install llvm. Thanks for your help!
