### ISSUE TITLE
Cannot import tslearn.shapelets

### ISSUE THREAD

**Issue by matthiasstorr** [tslearn-team/tslearn#419]
**Describe the bug**
when `import tslearn.shapelets` following error occurs: ` [...] in init tslearn.metrics.soft_dtw_fast()` `ImportError: numpy.core.multiarray failed to import`

**To Reproduce**
`import tslearn.shapelets`

**Expected behavior**
Successful import of package

**Environment (please complete the following information):**
 - OS: MacOS Monterey 12.5
 - tslearn version: 0.52 installed via `pip install git+https://github.com/tslearn-team/tslearn` cf. Issue [#418](https://github.com/tslearn-team/tslearn/issues/418)
 - numpy version: 1.22.4

**Comment by rtavenar** [comment]
Hi @matthiasstorr 

Could you provide the full error message?

Also, [this thread](https://github.com/numpy/numpy/issues/21055) suggests it could be a problem related to M1, could you try:

```
python -m pip install --upgrade pip
```

then uninstall numpy and reinstall. And if it fails, could you try the other suggestions in the linked thread?

**Comment by matthiasstorr** [comment]
Hi @rtavenar 
thank you for your response.

I actually already did `python -m pip install --upgrade pip` and uninstalled and reinstalled numpy again because I needed to downgrade from version 1.23.0. I installed numpy after upgrading pip via `pip install numpy=1.22.4`

Comment to the linked thread:
Numpy as standalone and with other packages such as pandas, scikit-learn, etc. works flawlessly. 

Here the full error message. This error occurs also when I try to import other classes such as `import tslearn.clustering`

`
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File __init__.pxd:942, in numpy.import_array()

RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 import tslearn.shapelets

File ~/miniforge3/lib/python3.9/site-packages/tslearn/shapelets/__init__.py:10, in <module>
      1 """
      2 The :mod:`tslearn.shapelets` module gathers Shapelet-based algorithms.
      3 
   (...)
      7 details.
      8 """
---> 10 from .shapelets import LearningShapelets, ShapeletModel, \
     11     SerializableShapeletModel, grabocka_params_to_shapelet_size_dict
     13 __author__ = 'Romain Tavenard romain.tavenard[at]univ-rennes2.fr'
     15 __all__ = [
     16     "LearningShapelets", "ShapeletModel", "SerializableShapeletModel",
     17     "grabocka_params_to_shapelet_size_dict"
     18 ]

File ~/miniforge3/lib/python3.9/site-packages/tslearn/shapelets/shapelets.py:22, in <module>
     20 from ..utils import to_time_series_dataset, check_dims, ts_size
     21 from ..bases import BaseModelPackage, TimeSeriesBaseEstimator
---> 22 from ..clustering import TimeSeriesKMeans
     23 from ..preprocessing import TimeSeriesScalerMinMax
     25 __author__ = 'Romain Tavenard romain.tavenard[at]univ-rennes2.fr'

File ~/miniforge3/lib/python3.9/site-packages/tslearn/clustering/__init__.py:8, in <module>
      1 """
      2 The :mod:`tslearn.clustering` module gathers time series specific clustering
      3 algorithms.
   (...)
      6  details.
      7 """
----> 8 from .kshape import KShape
      9 from .utils import (EmptyClusterError, silhouette_score,
     10                     TimeSeriesCentroidBasedClusteringMixin)
     11 from .kmeans import (TimeSeriesKMeans, KernelKMeans,
     12                      GlobalAlignmentKernelKMeans)

File ~/miniforge3/lib/python3.9/site-packages/tslearn/clustering/kshape.py:11, in <module>
      9 from tslearn.preprocessing import TimeSeriesScalerMeanVariance
     10 from tslearn.utils import to_time_series_dataset, check_dims
---> 11 from tslearn.metrics import cdist_normalized_cc, y_shifted_sbd_vec
     12 from tslearn.bases import BaseModelPackage, TimeSeriesBaseEstimator
     14 from .utils import (TimeSeriesCentroidBasedClusteringMixin,
     15                     _check_no_empty_cluster, _compute_inertia,
     16                     _check_initial_guess, EmptyClusterError)

File ~/miniforge3/lib/python3.9/site-packages/tslearn/metrics/__init__.py:19, in <module>
     17 from .ctw import ctw_path, ctw, cdist_ctw
     18 from .sax import cdist_sax
---> 19 from .softdtw_variants import (cdist_soft_dtw, cdist_gak,
     20                                cdist_soft_dtw_normalized, gak, soft_dtw,
     21                                soft_dtw_alignment,
     22                                sigma_gak, gamma_soft_dtw, SquaredEuclidean,
     23                                SoftDTW)
     24 from .cycc import cdist_normalized_cc, y_shifted_sbd_vec
     26 __author__ = 'Romain Tavenard romain.tavenard[at]univ-rennes2.fr'

File ~/miniforge3/lib/python3.9/site-packages/tslearn/metrics/softdtw_variants.py:12, in <module>
     10 from .utils import _cdist_generic
     11 from .dtw_variants import dtw, dtw_path
---> 12 from .soft_dtw_fast import _soft_dtw, _soft_dtw_grad, \
     13     _jacobian_product_sq_euc
     15 __author__ = 'Romain Tavenard romain.tavenard[at]univ-rennes2.fr'
     17 GLOBAL_CONSTRAINT_CODE = {None: 0, "": 0, "itakura": 1, "sakoe_chiba": 2}

File tslearn/metrics/soft_dtw_fast.pyx:11, in init tslearn.metrics.soft_dtw_fast()

File __init__.pxd:944, in numpy.import_array()

ImportError: numpy.core.multiarray failed to import
`
