### ISSUE TITLE
Scalers inverse_trasnsform() function

### ISSUE THREAD

**Issue by Lingkangjin** [tslearn-team/tslearn#466]
**Problem**
Is it possibile to transform back  after the machine learning process,
for instance I did the preprocessing of my data using "TimeSeriesScalerMeanVariance()" and did k-means clustering, therefore I have found the clusters centroids, however I could not to get back to original data, i.e. inverse of "TimeSeriesScalerMeanVariance()", is there solution to this?

**Describe the solution you'd like**
I would like to have something like Scikitlearn based method, which allows to inverse back directly

**Comment by rtavenar** [comment]
Dear @Lingkangjin 

There is no such thing as a general inverse transform in this case, since scaling is done per series, as mentionned in the docs.

**Comment by Lingkangjin** [comment]
Dear @rtavenar,

Thanks for the prompt response,
Well noted
