### ISSUE TITLE
[BUG] `cdist_soft_dtw_normalized` fails unexpectedly when time series panels have different number of instances

### ISSUE THREAD

**Issue by fkiraly** [tslearn-team/tslearn#475]
**Describe the bug**
`cdist_soft_dtw_normalized` fails with an exception when time series panels with different number of instances are provided to it.

This behaviour is different from `cdist_soft_dtw` where the same code does not fail, so I assume it is a but rather than an interface limitation.

**To Reproduce**

```python
from tslearn.metrics import cdist_soft_dtw_normalized

import numpy as np

arr = np.array([[1, 2], [2, 3], [3, 4]])

X = [arr, arr]
X2 = [arr, arr, arr]

cdist_soft_dtw_normalized(X, X2)
```

**Expected behavior**
The above should return a 2 x 3 `np.array` of `float`-s, just as the same call with `cdist_soft_dtw`

**Environment (please complete the following information):**
 - OS: windows, python 3.11
 - tslearn version 0.6.1

**Additional context**
Surfaced through systematic testing in a draft for an `sktime` adapter here: https://github.com/sktime/sktime/pull/5039

**Comment by rtavenar** [comment]
@YannCabanes could you have a look?

Also, the current implementation of `cdist_soft_dtw_normalized` seems buggy to me in the case where `dataset2` is provided (in this case, the self-distances are not stored on the diagonal but have to be computed explicitly). This later bug seems to have existed for a while (it was already present in v0.3 at least).

**Comment by rtavenar** [comment]
OK, I gave it a try in #476, let's see what tests have to say...

**Comment by fkiraly** [comment]
@rtavenar, thanks!

Quick question on tests - do you have systematic contract tests for distances?
Odd that it did not seem to cover such a central case (`dataset2` is non-null)

What I mean is a test that automatically gets all distances, then substitutes common cases for `dataset`, `dataset2` for it. We do that in `sktime` - using `skbase` (https://github.com/sktime/skbase) makes it relatively easy. Happy to help setting this up in `tslearn` if you'd like? I have not looked at your tests though - in case you're already doing this, please disregard my comment.
