### ISSUE TITLE
Got a message "NoneType has no atribute 'values'" when trying to extract the shapelets

### ISSUE THREAD

**Issue by stephanielees** [tslearn-team/tslearn#495]
Hi, I ran into an error message when I tried to get the shapelets after fitting `LearningShapelets` to my data. I know how many shapelets I got by looking at the transformed data, but I can't get the shapelets.

More specifically, I got the message after running this code:
`trans = LearningShapelets()`
`trans.fit(train_X, train_y)`
`trans.shapelets_`

It seems like the `LearningShapelets` class stores the shapelets in `shapelets_` as NoneType. However, the documentation says that the attribute should be a numpy ndarray. Is it just me? What should I do to get the shapelets?

Environment information:
 - Kaggle notebook
 - tslearn version [e.g. 0.6.2]

**Comment by YannCabanes** [comment]
Hello @stephanielees, thank you for your bug report.

I obtain the same error message when run the following code:
```
import numpy
from sklearn.metrics import accuracy_score
import tensorflow as tf
import matplotlib.pyplot as plt

from tslearn.datasets import CachedDatasets
from tslearn.preprocessing import TimeSeriesScalerMinMax
from tslearn.shapelets import LearningShapelets, \
    grabocka_params_to_shapelet_size_dict
from tslearn.utils import ts_size

# Set seed for determinism
numpy.random.seed(0)

# Load the Trace dataset
X_train, y_train, X_test, y_test = CachedDatasets().load_dataset("Trace")

# Normalize each of the timeseries in the Trace dataset
X_train = TimeSeriesScalerMinMax().fit_transform(X_train)
X_test = TimeSeriesScalerMinMax().fit_transform(X_test)

# Get statistics of the dataset
n_ts, ts_sz = X_train.shape[:2]
n_classes = len(set(y_train))

# Set the number of shapelets per size as done in the original paper
shapelet_sizes = grabocka_params_to_shapelet_size_dict(n_ts=n_ts,
                                                       ts_sz=ts_sz,
                                                       n_classes=n_classes,
                                                       l=0.1,
                                                       r=1)

# Define the model using parameters provided by the authors (except that we
# use fewer iterations here)
shp_clf = LearningShapelets(optimizer=tf.optimizers.Adam(.01),
                                                    batch_size=16,
                                                    weight_regularizer=.01,
                                                    max_iter=200,
                                                    random_state=42,
                                                    verbose=0)
shp_clf.fit(X_train, y_train)
shp_clf.shapelets_
```

This code is inspired by the following example of usage of `LearningShapelets` from the documentation:
https://tslearn.readthedocs.io/en/stable/auto_examples/classification/plot_shapelets.html#sphx-glr-auto-examples-classification-plot-shapelets-py

The error appeared when I removed `n_shapelets_per_size=shapelet_sizes` from the input parameters of the class `LearningShapelets`.

According to the documentation:
https://tslearn.readthedocs.io/en/stable/gen_modules/shapelets/tslearn.shapelets.LearningShapelets.html#tslearn.shapelets.LearningShapelets
by default, `n_shapelets_per_size=None`.

The first lines of the attribute `shp_clf.shapelets_` are:
```
    @property
    def shapelets_(self):
        total_n_shp = sum(self.n_shapelets_per_size.values())
```

When `n_shapelets_per_size` is `None`, this last line returns the following error message:
```
AttributeError: 'NoneType' object has no attribute 'values'
```

**Comment by YannCabanes** [comment]
I have opened the PR https://github.com/tslearn-team/tslearn/pull/498 to solve this issue.

**Comment by rtavenar** [comment]
Hi @YannCabanes and thanks for your work on this one.
Since the PR is now merged in main, do you think we should release a bugfix version?

**Comment by YannCabanes** [comment]
Hello @stephanielees, this issue is solved in tslearn 0.6.3 which has just been released on PyPI (on December 12, 2023). 
Thanks a lot for your bug report!

**Comment by stephanielees** [comment]
Hello @YannCabanes, I just tried out the latest version and it works now. Thank you so much! This would help a lot in my project.

**Comment by stephanielees** [comment]
Hello @YannCabanes, I just tried out the latest version and it works now. Thank you so much! This would help a lot in my project.
