### ISSUE TITLE
UCR_UEA_datasets().list_univariate_datasets() and UCR_UEA_datasets().load_dataset() and Failed

### ISSUE THREAD

**Issue by LbzSteven** [tslearn-team/tslearn#516]
**Describe the bug**
When I call the function UCR_UEA_datasets().list_univariate_datasets(), it failed at:
![image](https://github.com/tslearn-team/tslearn/assets/43373047/c2e83aff-05d2-4237-adc5-cf477d08fe07)
Also, many of the datasets I could not load correctly.

**Environment (please complete the following information):**
 - OS: [linux]
 - tslearn version [e.g. 0.6.3]

**Comment by LbzSteven** [comment]
The tslearn version is 0.6.3

**Comment by LbzSteven** [comment]
I think the issue is www.timeseriesclassification.com website is down right now. Just wonder if we have other resorts.

**Comment by nkchangshu** [comment]
URLError: <urlopen error [Errno -2] Name or service not known> I encountered the same issue, and the URL www.timeseriesclassification.com is not accessible. Please help update the source or upload the dataset to GitHub as soon as possible. Thank you very much.

**Comment by YannCabanes** [comment]
Hello @LbzSteven and @nkchangshu,

Thanks for opening an issue. 
It seems that the URL https://www.timeseriesclassification.com/index.php is not done anymore, but it is written on the home page of the website that: "This website has been down for a while."

Using Google Colab, after installing `tslearn` running `!pip install tslearn`, I can run:
```
from tslearn.datasets import UCR_UEA_datasets

X_train, y_train, X_test, y_test = UCR_UEA_datasets().load_dataset("TwoPatterns")

print(X_train.shape)  # (1000, 128, 1)
print(y_train.shape)  # (1000,)

ucr_uea_list_univariate_datasets = UCR_UEA_datasets().list_univariate_datasets()
print(ucr_uea_list_univariate_datasets)  # []

ucr_uea_list_multivariate_datasets = UCR_UEA_datasets().list_multivariate_datasets()
print(ucr_uea_list_univariate_datasets)  # []
```

It seems that the univariate and multivariate dataset lists are empty, but it is still possible to import the datasets using their names.

The following web pages can be useful to look for the dataset names and features:
- https://www.timeseriesclassification.com/dataset.php
- https://www.cs.ucr.edu/~eamonn/time_series_data_2018/
- https://zenodo.org/communities/tsml/records?q=&f=subject%3Aucr%20archive&f=subject%3Auea%20archive&l=list&p=1&s=10&sort=newest

**Comment by YannCabanes** [comment]
Hello @LbzSteven and @nkchangshu,
This issue has been solved in the PR https://github.com/tslearn-team/tslearn/pull/517.
Thanks for reporting this problem!
